In [1]:
import pandas as np
laptops=np.read_csv('/home/maxpgn/Documents/Python/'laptops.csv',index_col=False,na_filter=False,encoding='latin-1')
laptops.rename({' Storage':'storage'},axis=1,inplace=True)

In [2]:
#storage 1 capacity creation with temporary name
laptops['s1']=(laptops['storage']
               .str.split(n=2,expand=True)
               .loc[:,0]
              )

In [3]:
#boolean of storage 1 in GB
s1GB=laptops['s1'].str.contains('GB')

#storage 1 in GB and TB conversion to float
laptops['s1']=(laptops['s1']   
                        .str.replace('GB','')
                        .str.replace('TB','')
                        .astype(float)
                        )

#storage 1 in TB conversion to GB
laptops.loc[~s1GB,'s1']=(laptops.loc[~s1GB,'s1']
                        *1000
                        )
laptops.info()
laptops['s1'].unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 14 columns):
Manufacturer                1303 non-null object
Model Name                  1303 non-null object
Category                    1303 non-null object
Screen Size                 1303 non-null object
Screen                      1303 non-null object
CPU                         1303 non-null object
RAM                         1303 non-null object
storage                     1303 non-null object
GPU                         1303 non-null object
Operating System            1303 non-null object
Operating System Version    1303 non-null object
Weight                      1303 non-null object
Price (Euros)               1303 non-null object
s1                          1303 non-null float64
dtypes: float64(1), object(13)
memory usage: 142.6+ KB


array([1.28e+02, 2.56e+02, 5.12e+02, 5.00e+02, 1.00e+03, 3.20e+01,
       6.40e+01, 2.00e+03, 1.60e+01, 1.00e+00, 2.40e+02, 8.00e+00,
       5.08e+02])

In [4]:
#storage 1 type creation with temporary name
laptops['s1t']=(laptops['storage']
                .str.split(n=2,expand=True)
                .loc[:,1]
                #.str.strip()
               )

In [5]:
#boolean of laptops with 2 disks
tdb=laptops['storage'].str.contains('\+')

#storage 2 capacity creation with temporary name
laptops.loc[tdb,'s2']=(laptops['storage']
                       .str.rsplit(n=2,expand=True)
                       .loc[:,1]
                      )

In [6]:
#boolean of storage 2 in either GB or TB
#s2GB=(laptops['s2'].notna()) & (laptops['s2'].str.contains('GB'))
s2TB=(laptops['s2'].notna()) & (laptops['s2'].str.contains('TB'))

#storage 2 conversion to float
laptops['s2']=(laptops['s2']
               .str.replace('GB','')
               .str.replace('TB','')
               .astype(float)
               )
laptops.loc[s2TB,'s2']=(laptops.loc[s2TB,'s2']
                        *1000
                       )

laptops.info()
laptops['s2'].unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 16 columns):
Manufacturer                1303 non-null object
Model Name                  1303 non-null object
Category                    1303 non-null object
Screen Size                 1303 non-null object
Screen                      1303 non-null object
CPU                         1303 non-null object
RAM                         1303 non-null object
storage                     1303 non-null object
GPU                         1303 non-null object
Operating System            1303 non-null object
Operating System Version    1303 non-null object
Weight                      1303 non-null object
Price (Euros)               1303 non-null object
s1                          1303 non-null float64
s1t                         1303 non-null object
s2                          208 non-null float64
dtypes: float64(2), object(14)
memory usage: 163.0+ KB


array([  nan, 1000.,  256., 2000.,  500.,  512.])

In [7]:
#storage 2 type creation with temporary name
laptops['s2t']=(laptops.loc[tdb,'storage']
                .str.rsplit(n=2,expand=True)
                .loc[:,2]
                #.str.strip()
               )

laptops.loc[~tdb,'s2t']=None

In [8]:
#column renaming
rename_dict={
    's1':'storage_1_capacity_gb',
    's1t':'storage_1_type',
    's2':'storage_2_capacity_gb',
    's2t':'storage_2_type'
}
laptops.rename(rename_dict,axis=1,inplace=True)
    
#dropping 'storage' column
laptops=laptops.drop('storage',axis=1)

In [9]:
laptops.loc[76:81,['storage_1_capacity_gb','storage_1_type','storage_2_capacity_gb','storage_2_type']]

storage_1_capacity_gb storage_1_type  storage_2_capacity_gb storage_2_type
76                 2000.0            HDD                    NaN           None
77                  128.0            SSD                 1000.0            HDD
78                 1000.0            HDD                    NaN           None
79                  128.0            SSD                 1000.0            HDD
80                  256.0            SSD                    NaN           None
81                  512.0            SSD                    NaN           None

In [10]:
laptops.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 17 columns):
Manufacturer                1303 non-null object
Model Name                  1303 non-null object
Category                    1303 non-null object
Screen Size                 1303 non-null object
Screen                      1303 non-null object
CPU                         1303 non-null object
RAM                         1303 non-null object
storage                     1303 non-null object
GPU                         1303 non-null object
Operating System            1303 non-null object
Operating System Version    1303 non-null object
Weight                      1303 non-null object
Price (Euros)               1303 non-null object
storage_1_capacity_gb       1303 non-null float64
storage_1_type              1303 non-null object
storage_2_capacity_gb       208 non-null float64
storage_2_type              208 non-null object
dtypes: float64(2), object(15)
memory usage: 173.1+ KB


In [11]:
laptops['storage_1_capacity_gb'].unique()

array([1.28e+02, 2.56e+02, 5.12e+02, 5.00e+02, 1.00e+03, 3.20e+01,
       6.40e+01, 2.00e+03, 1.60e+01, 1.00e+00, 2.40e+02, 8.00e+00,
       5.08e+02])

In [12]:
laptops['storage_1_type'].unique()

array(['SSD', 'Flash', 'HDD', 'Hybrid'], dtype=object)

In [13]:
laptops['storage_2_capacity_gb'].unique()

array([  nan, 1000.,  256., 2000.,  500.,  512.])

In [14]:
laptops['storage_2_type'].unique()

array([None, 'HDD', 'SSD', 'Hybrid'], dtype=object)